### ISSUE TITLE
Tempo is not broadcasted to clients

### ISSUE THREAD

**Issue by DerouineauNicolas** [xavierfav/multi-web-audio-sequencer#12]
To be fixed.

**Comment by xavierfav** [comment]
In _server.js_:
- Add `tempo` propriety in `sequncerState`.
- Add socket.on('tempo', function (message) {...}) method for receiving tempo changes, changing the tempo in the according sequencer state from `sequencerStates` and broadcasting the tempo. This function should be declared in the callback of `socket.on('room', ... )` corresponding to a room connection.

In _index.ejs_:
- Add `sendTempo(trackId, tempo)` function that emit a 'tempo' socket to the server.
- Add `socket.on('sendTempo', function (message) {...})` that changes the tempo in the client sequencer.

In _app.js_:
- Call `sendTempo(trackId, tempo)` in `changeTempoListener()`.
