### ISSUE TITLE
Display error message if no results found

### ISSUE THREAD

**Issue by DerouineauNicolas** [xavierfav/multi-web-audio-sequencer#19]
At the moment, no message is displayed if the freesound's request returns nothing. We should add a message to warn the user.

**Comment by xavierfav** [comment]
I don't see why is this useful.
Moreover, having no result is not an error.

What happen when the search does not retrieve any result is that no result are displayed. Also, the total number of page displayed is 0. Maybe we could just add something telling the total number of sounds, so it makes it clear in any case. 

This would be done just by adding an if statement in the `Search.prototype.searchFreesound` method in the `freesound.textSearch`callback.

**Comment by DerouineauNicolas** [comment]
In the end, 358dc89d4a59956b32baff8bfb1bc7446a48d626 improved the readbility. Moreover , this issue overlaps with issues #6 and #49.
