### ISSUE TITLE
Add rooms

### ISSUE THREAD

**Issue by xavierfav** [xavierfav/multi-web-audio-sequencer#2]
For now, all the users that connect to the app access the same sequencer.
It would be nice to be able to manage rooms as a user.

To start, we can just make available several rooms, each of them containing a sequencer (in its associated state). The states should be store in the server, and sent to users when they connect to a room.

In the future, it would be nice to have a login functionality, allows user to create their own rooms, give access to other users, etc...

**Comment by DerouineauNicolas** [comment]
It could be useful also to display the number of users in a given room.

**Comment by xavierfav** [comment]
This seems seems interesting: https://www.tutorialspoint.com/socket.io/socket.io_rooms.htm

**Comment by valou5940** [comment]
I think the code will be changed as this : 

- Server side (server.js) :  socket.in(roomNumber).emit...
- .in(roomNumber) allows to send the event to a defined room

- I'll add a button and an input to choose and submit in which room the user wants to go

**Comment by xavierfav** [comment]
Seems nice.
You will need also to have different _sequencer state_, and apply the modifications to the right one, knowing the `roomNumber`
