### ISSUE TITLE
Export loop as opus audio file 

### ISSUE THREAD

**Issue by valou5940** [xavierfav/multi-web-audio-sequencer#27]
It would be nice to be able to export the loop created as a downloadable file stored in the user's computer.

I think the Web Audi API can do the trick : 

https://developer.mozilla.org/fr/docs/Web/API/AudioContext/createMediaStreamDestination

As for the front, just add an export button in the  search container.

What do you think ?

**Comment by DerouineauNicolas** [comment]
You should be aware that you'll need external dependancies to encode the PCM output to MP3.

**Comment by DerouineauNicolas** [comment]
Let's try with opus first.
