### ISSUE TITLE
Add new tracks

### ISSUE THREAD

**Issue by valou5940** [xavierfav/multi-web-audio-sequencer#4]
- Possibility to add new tracks

- How we could implements this :

1. Add a  "new track" button in index.ejs and an input with the name of the track
2. In app.js, add a function triggered when click on "new track" which inserts after the last track the same HTML code than the previous track.
Issues => the state must be null
In the future it could be interesting to have the choice where the user wants to put the track, or implements a drag n drop
3. We'll have to slightly change toggleSelectedListener() and toggleSelectedListenerSocket() to be dynamic !

**Comment by xavierfav** [comment]
It is now possible to add new tracks.
Moreover, we can search sound from Freesound, and load them in a track.

However, there is one bug with the actual code. It is possible to add tracks that have the same name as another one, making the sequencer to behave in a strange manner.
We have to avoid adding tracks with the same name of another already created.
