### ISSUE TITLE
Presets for guitar, violin etc.

### ISSUE THREAD

**Issue by surikov** [xavierfav/multi-web-audio-sequencer#47]
Use WebAudioFont to play sounds. It has about 2000 of musical instruments. 
See example https://surikov.github.io/webaudiofont/examples/dynamic.html

**Comment by xavierfav** [comment]
Thanks! This could be nice indeed.
However, it would need some work on the interface to allow people to either search Freesound or WebAudioFont. Not sure what would be the best way (mixing the different sound providers in the same search engine environment, or proposing two different sections).

For now, I think we will stay on using Freesound, for the which we plan to propose better search options #7, and use content based analysis #33.
